#pragma once

#include <stddef.h>
#include <stdint.h>

// Drives an I2S DAC/amp (e.g. a MAX98357A) wired to this board's own I2S
// output for simple mono audio playback - see docs/audio-i2s-wiring.md for
// wiring. Mirrors firmware/src/audio/i2s_player.h's RP2040-side API and
// design tradeoffs (blocking playback, one fixed sample rate set once at
// boot and never reconfigured), even though the two implementations sit
// on top of quite different I2S hardware.
namespace I2sPlayer {

// Brings up I2S at the fixed sample rate every clip and the test tone are
// authored at (see kSampleRate in i2s_player.cpp) - call once from
// setup().
void begin();

// Plays a short two-note test chime, synthesized on the fly - no audio
// asset needed, just proves the DAC/amp/speaker chain works at all.
void playTestTone();

// Plays a mono 16-bit PCM clip (e.g. one generated by
// tools/convert_wav_to_pcm.py into esp32-bridge/src/assets/). sampleRate
// must match the fixed rate I2S was begin()'d at, or this refuses to play
// it rather than silently mis-pitching it.
void playClip(const int16_t *samples, size_t length, uint32_t sampleRate);

} // namespace I2sPlayer
