#pragma once

#include <stddef.h>
#include <stdint.h>

// Drives an I2S DAC/amp (e.g. a MAX98357A) wired to the RP2040's PIO-based
// I2S output for simple mono audio playback - see
// docs/audio-i2s-wiring.md for wiring. Playback is blocking (a clip or
// test tone takes over the CPU for its own duration - no face animation,
// button, or serial polling happens meanwhile), which is fine for the
// short clips this is meant for; a longer/overlapping-audio use case would
// need a non-blocking, DMA-callback-driven rewrite instead.
namespace I2sPlayer {

// Brings up the I2S output at the fixed sample rate every clip and the
// test tone are authored at (see kSampleRate in i2s_player.cpp) - call
// once from setup(). Deliberately never torn down/reconfigured afterward:
// see docs/esp32-network-bridge.md's account of a PIO-adjacent peripheral
// (UART1) hanging the chip when reconfigured live - I2S is also
// PIO-based, and there's no reason to assume it would be any more
// forgiving of the same mistake, so this firmware just doesn't try it.
void begin();

// Plays a short two-note test chime, synthesized on the fly - no audio
// asset needed, just proves the DAC/amp/speaker chain works at all.
void playTestTone();

// Plays a mono 16-bit PCM clip (e.g. one generated by
// tools/convert_wav_to_pcm.py into firmware/src/assets/). sampleRate must
// match the fixed rate I2S was begin()'d at, or this refuses to play it
// (rather than silently mis-pitching it) - see the array's own generated
// _sample_rate constant.
void playClip(const int16_t *samples, size_t length, uint32_t sampleRate);

} // namespace I2sPlayer
